# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cghubdownloader.ui'
#
# Created: Thu Sep 05 17:31:56 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CGHubDownloader(object):
    def setupUi(self, CGHubDownloader):
        CGHubDownloader.setObjectName(_fromUtf8("CGHubDownloader"))
        CGHubDownloader.resize(670, 481)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/appicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CGHubDownloader.setWindowIcon(icon)
        CGHubDownloader.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(CGHubDownloader)
        self.centralwidget.setStyleSheet(_fromUtf8("/*QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(218, 218, 218, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}*/\n"
"\n"
"QListWidget, QListView, QTableWidget, QTableView, QLineEdit {\n"
"    border: 1px solid #b7d9ed;\n"
"}\n"
"\n"
"QGroupBox {\n"
"   border: none;\n"
"}\n"
""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setMargin(7)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.download_buttonWidget = QtGui.QToolButton(self.widget)
        self.download_buttonWidget.setMinimumSize(QtCore.QSize(50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_buttonWidget.setIcon(icon1)
        self.download_buttonWidget.setIconSize(QtCore.QSize(50, 50))
        self.download_buttonWidget.setAutoRaise(True)
        self.download_buttonWidget.setObjectName(_fromUtf8("download_buttonWidget"))
        self.verticalLayout_4.addWidget(self.download_buttonWidget)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setLineWidth(0)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.setproject_buttonWidget = QtGui.QToolButton(self.widget)
        self.setproject_buttonWidget.setMinimumSize(QtCore.QSize(50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/project.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setproject_buttonWidget.setIcon(icon2)
        self.setproject_buttonWidget.setIconSize(QtCore.QSize(50, 50))
        self.setproject_buttonWidget.setAutoRaise(True)
        self.setproject_buttonWidget.setObjectName(_fromUtf8("setproject_buttonWidget"))
        self.verticalLayout_4.addWidget(self.setproject_buttonWidget)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.tableview_buttonWidget = QtGui.QToolButton(self.widget)
        self.tableview_buttonWidget.setMinimumSize(QtCore.QSize(50, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/tableview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tableview_buttonWidget.setIcon(icon3)
        self.tableview_buttonWidget.setIconSize(QtCore.QSize(50, 50))
        self.tableview_buttonWidget.setAutoRaise(True)
        self.tableview_buttonWidget.setObjectName(_fromUtf8("tableview_buttonWidget"))
        self.verticalLayout_4.addWidget(self.tableview_buttonWidget)
        self.thumbnailview_buttonWidget = QtGui.QToolButton(self.widget)
        self.thumbnailview_buttonWidget.setMinimumSize(QtCore.QSize(50, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/thumbnailview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.thumbnailview_buttonWidget.setIcon(icon4)
        self.thumbnailview_buttonWidget.setIconSize(QtCore.QSize(50, 50))
        self.thumbnailview_buttonWidget.setAutoRaise(True)
        self.thumbnailview_buttonWidget.setObjectName(_fromUtf8("thumbnailview_buttonWidget"))
        self.verticalLayout_4.addWidget(self.thumbnailview_buttonWidget)
        self.localview_buttonWidget = QtGui.QToolButton(self.widget)
        self.localview_buttonWidget.setMinimumSize(QtCore.QSize(50, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/localview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.localview_buttonWidget.setIcon(icon5)
        self.localview_buttonWidget.setIconSize(QtCore.QSize(50, 50))
        self.localview_buttonWidget.setAutoRaise(True)
        self.localview_buttonWidget.setObjectName(_fromUtf8("localview_buttonWidget"))
        self.verticalLayout_4.addWidget(self.localview_buttonWidget)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.avatarhold_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatarhold_widget.sizePolicy().hasHeightForWidth())
        self.avatarhold_widget.setSizePolicy(sizePolicy)
        self.avatarhold_widget.setMinimumSize(QtCore.QSize(0, 80))
        self.avatarhold_widget.setMaximumSize(QtCore.QSize(140, 16777215))
        self.avatarhold_widget.setObjectName(_fromUtf8("avatarhold_widget"))
        self.avatar_buttonWidget = QtGui.QToolButton(self.avatarhold_widget)
        self.avatar_buttonWidget.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.avatar_buttonWidget.setText(_fromUtf8(""))
        self.avatar_buttonWidget.setIconSize(QtCore.QSize(50, 50))
        self.avatar_buttonWidget.setAutoRaise(False)
        self.avatar_buttonWidget.setObjectName(_fromUtf8("avatar_buttonWidget"))
        self.verticalLayout_3.addWidget(self.avatarhold_widget)
        self.username_labelWidget = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_labelWidget.sizePolicy().hasHeightForWidth())
        self.username_labelWidget.setSizePolicy(sizePolicy)
        self.username_labelWidget.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semibold"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username_labelWidget.setFont(font)
        self.username_labelWidget.setAlignment(QtCore.Qt.AlignCenter)
        self.username_labelWidget.setObjectName(_fromUtf8("username_labelWidget"))
        self.verticalLayout_3.addWidget(self.username_labelWidget)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setMargin(7)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.users_listViewWidget = QtGui.QListView(self.groupBox)
        self.users_listViewWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.users_listViewWidget.setFont(font)
        self.users_listViewWidget.setTabKeyNavigation(False)
        self.users_listViewWidget.setIconSize(QtCore.QSize(0, 0))
        self.users_listViewWidget.setSpacing(0)
        self.users_listViewWidget.setObjectName(_fromUtf8("users_listViewWidget"))
        self.verticalLayout.addWidget(self.users_listViewWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.newuser_lineEditWidget = QtGui.QLineEdit(self.groupBox)
        self.newuser_lineEditWidget.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.newuser_lineEditWidget.setFont(font)
        self.newuser_lineEditWidget.setText(_fromUtf8(""))
        self.newuser_lineEditWidget.setReadOnly(False)
        self.newuser_lineEditWidget.setObjectName(_fromUtf8("newuser_lineEditWidget"))
        self.horizontalLayout_3.addWidget(self.newuser_lineEditWidget)
        self.adduser_buttonWidget = QtGui.QPushButton(self.groupBox)
        self.adduser_buttonWidget.setMinimumSize(QtCore.QSize(25, 25))
        self.adduser_buttonWidget.setMaximumSize(QtCore.QSize(25, 25))
        self.adduser_buttonWidget.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adduser_buttonWidget.setIcon(icon6)
        self.adduser_buttonWidget.setObjectName(_fromUtf8("adduser_buttonWidget"))
        self.horizontalLayout_3.addWidget(self.adduser_buttonWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.images_tableViewWidget = MyTableView(self.page)
        self.images_tableViewWidget.setGeometry(QtCore.QRect(40, 40, 256, 192))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.images_tableViewWidget.setFont(font)
        self.images_tableViewWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.images_tableViewWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.images_tableViewWidget.setAlternatingRowColors(False)
        self.images_tableViewWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.images_tableViewWidget.setObjectName(_fromUtf8("images_tableViewWidget"))
        self.images_tableViewWidget.horizontalHeader().setDefaultSectionSize(250)
        self.images_tableViewWidget.horizontalHeader().setHighlightSections(False)
        self.images_tableViewWidget.horizontalHeader().setMinimumSectionSize(150)
        self.images_tableViewWidget.verticalHeader().setVisible(False)
        self.images_tableViewWidget.verticalHeader().setCascadingSectionResizes(False)
        self.images_tableViewWidget.verticalHeader().setDefaultSectionSize(27)
        self.images_tableViewWidget.verticalHeader().setMinimumSectionSize(20)
        self.images_tableViewWidget.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.thumbnails_tableViewWidget = MyThumbnailsView(self.page_2)
        self.thumbnails_tableViewWidget.setGeometry(QtCore.QRect(40, 60, 256, 192))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.thumbnails_tableViewWidget.setFont(font)
        self.thumbnails_tableViewWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.thumbnails_tableViewWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.thumbnails_tableViewWidget.setAlternatingRowColors(False)
        self.thumbnails_tableViewWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.thumbnails_tableViewWidget.setObjectName(_fromUtf8("thumbnails_tableViewWidget"))
        self.thumbnails_tableViewWidget.horizontalHeader().setVisible(False)
        self.thumbnails_tableViewWidget.horizontalHeader().setDefaultSectionSize(80)
        self.thumbnails_tableViewWidget.horizontalHeader().setHighlightSections(False)
        self.thumbnails_tableViewWidget.horizontalHeader().setMinimumSectionSize(80)
        self.thumbnails_tableViewWidget.verticalHeader().setVisible(False)
        self.thumbnails_tableViewWidget.verticalHeader().setCascadingSectionResizes(False)
        self.thumbnails_tableViewWidget.verticalHeader().setDefaultSectionSize(100)
        self.thumbnails_tableViewWidget.verticalHeader().setMinimumSectionSize(100)
        self.thumbnails_tableViewWidget.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        CGHubDownloader.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CGHubDownloader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.file_Menu = QtGui.QMenu(self.menubar)
        self.file_Menu.setObjectName(_fromUtf8("file_Menu"))
        self.help_Menu = QtGui.QMenu(self.menubar)
        self.help_Menu.setObjectName(_fromUtf8("help_Menu"))
        self.view_Menu = QtGui.QMenu(self.menubar)
        self.view_Menu.setObjectName(_fromUtf8("view_Menu"))
        CGHubDownloader.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CGHubDownloader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CGHubDownloader.setStatusBar(self.statusbar)
        self.setProject_Action = QtGui.QAction(CGHubDownloader)
        self.setProject_Action.setObjectName(_fromUtf8("setProject_Action"))
        self.about_Action = QtGui.QAction(CGHubDownloader)
        self.about_Action.setObjectName(_fromUtf8("about_Action"))
        self.actionLog = QtGui.QAction(CGHubDownloader)
        self.actionLog.setCheckable(True)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.test_action = QtGui.QAction(CGHubDownloader)
        self.test_action.setObjectName(_fromUtf8("test_action"))
        self.openDatViewer_action = QtGui.QAction(CGHubDownloader)
        self.openDatViewer_action.setObjectName(_fromUtf8("openDatViewer_action"))
        self.file_Menu.addAction(self.setProject_Action)
        self.menubar.addAction(self.file_Menu.menuAction())
        self.menubar.addAction(self.view_Menu.menuAction())
        self.menubar.addAction(self.help_Menu.menuAction())

        self.retranslateUi(CGHubDownloader)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CGHubDownloader)
        CGHubDownloader.setTabOrder(self.newuser_lineEditWidget, self.adduser_buttonWidget)
        CGHubDownloader.setTabOrder(self.adduser_buttonWidget, self.users_listViewWidget)
        CGHubDownloader.setTabOrder(self.users_listViewWidget, self.download_buttonWidget)
        CGHubDownloader.setTabOrder(self.download_buttonWidget, self.setproject_buttonWidget)
        CGHubDownloader.setTabOrder(self.setproject_buttonWidget, self.tableview_buttonWidget)
        CGHubDownloader.setTabOrder(self.tableview_buttonWidget, self.thumbnailview_buttonWidget)
        CGHubDownloader.setTabOrder(self.thumbnailview_buttonWidget, self.localview_buttonWidget)
        CGHubDownloader.setTabOrder(self.localview_buttonWidget, self.avatar_buttonWidget)

    def retranslateUi(self, CGHubDownloader):
        CGHubDownloader.setWindowTitle(QtGui.QApplication.translate("CGHubDownloader", "CGHub Downloader", None, QtGui.QApplication.UnicodeUTF8))
        self.download_buttonWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Download this user\'s images", None, QtGui.QApplication.UnicodeUTF8))
        self.download_buttonWidget.setText(QtGui.QApplication.translate("CGHubDownloader", "Dwnld", None, QtGui.QApplication.UnicodeUTF8))
        self.setproject_buttonWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Set download location", None, QtGui.QApplication.UnicodeUTF8))
        self.setproject_buttonWidget.setText(QtGui.QApplication.translate("CGHubDownloader", "Set Proj", None, QtGui.QApplication.UnicodeUTF8))
        self.tableview_buttonWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Switch to table view", None, QtGui.QApplication.UnicodeUTF8))
        self.tableview_buttonWidget.setText(QtGui.QApplication.translate("CGHubDownloader", "List Vu", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbnailview_buttonWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Switch to thumbnail view", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbnailview_buttonWidget.setText(QtGui.QApplication.translate("CGHubDownloader", "Thumb", None, QtGui.QApplication.UnicodeUTF8))
        self.localview_buttonWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Switch to local folder view", None, QtGui.QApplication.UnicodeUTF8))
        self.localview_buttonWidget.setText(QtGui.QApplication.translate("CGHubDownloader", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.username_labelWidget.setText(QtGui.QApplication.translate("CGHubDownloader", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.users_listViewWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Click on user\'s name to see user\'s images list on the right", None, QtGui.QApplication.UnicodeUTF8))
        self.newuser_lineEditWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Type in CGHub user\'s name here", None, QtGui.QApplication.UnicodeUTF8))
        self.adduser_buttonWidget.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "Add user to list", None, QtGui.QApplication.UnicodeUTF8))
        self.file_Menu.setTitle(QtGui.QApplication.translate("CGHubDownloader", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.help_Menu.setTitle(QtGui.QApplication.translate("CGHubDownloader", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.view_Menu.setTitle(QtGui.QApplication.translate("CGHubDownloader", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.setProject_Action.setText(QtGui.QApplication.translate("CGHubDownloader", "Set download location", None, QtGui.QApplication.UnicodeUTF8))
        self.about_Action.setText(QtGui.QApplication.translate("CGHubDownloader", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog.setText(QtGui.QApplication.translate("CGHubDownloader", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.test_action.setText(QtGui.QApplication.translate("CGHubDownloader", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.openDatViewer_action.setText(QtGui.QApplication.translate("CGHubDownloader", "View database", None, QtGui.QApplication.UnicodeUTF8))
        self.openDatViewer_action.setToolTip(QtGui.QApplication.translate("CGHubDownloader", "View database (\'Users.dat\')", None, QtGui.QApplication.UnicodeUTF8))

from mythumbnailsview import MyThumbnailsView
from mytableview import MyTableView
import resources_rc
